# Part 1: Theoretical Questions

## 1. What are the different data structures used in Tensorflow?. Give some examples

**Data Structures in TensorFlow:**

1. **Tensors:** Tensors are the primary data structure in TensorFlow, representing the data as multi-dimensional arrays. These can be constants or variables, holding the data manipulated during computation.

2. **Graphs:** TensorFlow uses computational graphs to represent the flow of data. These graphs consist of a series of nodes, each representing an operation, and edges representing the flow of tensors between these operations.

3. **Variables:** Variables in TensorFlow are used to store and update parameters during the optimization process. These are typically used for model weights and biases that change during training.

4. **Constants:** Constants are immutable tensors whose values cannot be changed during the execution of a graph. These are used for fixed values such as hyperparameters or fixed inputs.

In [1]:
#Tensors: A 2x2 tensor in TensorFlow: 
import tensorflow as tf

tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [4]:
#Graphs:Defining a simple computational graph:

a = tf.constant(5)
b = tf.constant(2)
c = tf.multiply(a, b)

c

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
#variable
var = tf.Variable(3.0)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [7]:
#constant
const = tf.constant(10)
const

<tf.Tensor: shape=(), dtype=int32, numpy=10>

## 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

**Difference between TensorFlow Constant and Variable:**

TensorFlow Constants are immutable, meaning their values cannot change. They are used to hold constant values such as hyperparameters or fixed inputs. For example, if you define a constant as `a = tf.constant(5)`, the value of `a` will always be 5 during the execution of the graph.

TensorFlow Variables, on the other hand, are used to store and update parameters during the optimization process, such as model weights and biases that change during training. For example, if you define a variable as `b = tf.Variable(3.0)`, you can update its value using operations like `assign` or `assign_add`.

## 3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

**1. Addition**

Matrix addition in TensorFlow is done using the tf.add function. It is an element wise operation which adds each corresponding elements respectively Here's an example:

In [10]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

C = tf.add(A, B)

C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

**2. Matrix Multiplication**
    
Matrix multiplication in TensorFlow is done using the tf.matmul function. It performs a matrix multiplication which is a vector product. Here's an example:

In [11]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

C = tf.matmul(A, B)

C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

**3. Element-wise Operations**

Element-wise operations in TensorFlow can be performed using various functions such as tf.add, tf.subtract, tf.multiply, and tf.divide. Here's an example of performing element-wise multiplication:

In [12]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

C = tf.multiply(A, B)

C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

# Part 2: Practical Implementation

## Task 1: Creating and Manipulating Matrice

## 1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A

In [13]:
A=tf.random.normal(shape=(3,3))
print(A)

tf.Tensor(
[[ 1.9181497  -1.3291092  -0.8183831 ]
 [ 1.1213195   1.5685526  -0.89117664]
 [-0.0724829  -1.355397    0.41017064]], shape=(3, 3), dtype=float32)


## 3. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [37]:
B=tf.random.truncated_normal([4,4])
print(B)

tf.Tensor(
[[-0.8618203  -0.8322235   0.9695119   0.38945365]
 [ 0.01134019 -0.02160602  0.65895146  0.22029424]
 [ 0.01374637  0.9393678   0.47552374 -0.58570683]
 [-0.24116395  0.4893404  -0.561031    0.45429933]], shape=(4, 4), dtype=float32)


## 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C

In [32]:
C=tf.random.normal(shape=(2,2) , mean=3, stddev=0.5)
C

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.3460484, 1.7692786],
       [2.8570044, 2.675232 ]], dtype=float32)>

## 4.  Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [46]:
A=tf.random.normal((3,3))
B=tf.random.normal((3,3))

In [47]:
D=tf.add(A,B)
D

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.1670585,  0.8429472, -1.0525469],
       [-2.6541073,  3.392046 ,  2.7256212],
       [ 1.1744564, -1.3815911, -3.5718431]], dtype=float32)>

## 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [49]:
C=tf.random.normal((3,3))

In [50]:
E=tf.matmul(C,D)
E

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.4139423 ,  0.25420985,  3.7953494 ],
       [-0.5246744 ,  0.9461523 , -0.3917484 ],
       [-2.6876078 ,  2.4337003 ,  0.22782496]], dtype=float32)>

## Task 2: Performing Additional Matrix Operation

## 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function

In [56]:
F=tf.random.uniform((2,2), 5,10)
F

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.6990438, 8.541239 ],
       [8.165007 , 8.930044 ]], dtype=float32)>

## 2. Calculate the transpose of matrix F and store the result in matrix G

In [59]:
G=tf.transpose(F)
G

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.6990438, 8.165007 ],
       [8.541239 , 8.930044 ]], dtype=float32)>

## 3. Calculate the element wise exponential of matrix F and store the result in matrix H

In [60]:
H=tf.exp(F)
H

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2206.2373, 5121.685 ],
       [3515.7446, 7555.599 ]], dtype=float32)>

## 4. Create a matrix I by concatenating matrix F and matrix G horizontally

In [65]:
I=tf.concat([F,G], axis=1)
I

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[7.6990438, 8.541239 , 7.6990438, 8.165007 ],
       [8.165007 , 8.930044 , 8.541239 , 8.930044 ]], dtype=float32)>

## 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [67]:
J=tf.concat([F,H], axis=0)
J

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[   7.6990438,    8.541239 ],
       [   8.165007 ,    8.930044 ],
       [2206.2373   , 5121.685    ],
       [3515.7446   , 7555.599    ]], dtype=float32)>